# Generated by Django 4.2.9 on 2025-01-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
