# Generated by Django 4.2.9 on 2025-01-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_annualplan_monthlyreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnualPlan',
        ),
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
    ]
