# Generated by Django 4.2.9 on 2025-04-02 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_type', models.CharField(choices=[('php_invest', 'PHP Invest Total'), ('php_reit', 'PHP REIT Fund Total')], max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('adjustment_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('affected_users_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='investment',
            name='card',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentcard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dark_mode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='notification',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='notification/'),
        ),
        migrations.AddField(
            model_name='user',
            name='php_invest_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='php_reit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='category',
            field=models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='PaymentCard',
        ),
        migrations.AddField(
            model_name='balanceadjustmentlog',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_adjustments', to=settings.AUTH_USER_MODEL),
        ),
    ]
