# Generated by Django 5.2 on 2025-04-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_balanceadjustmentlog_remove_investment_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Matnni kiriting')),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=500, verbose_name='Aloqa markazi')),
                ('call', models.CharField(max_length=13, verbose_name='Aloqa markazi')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=50, verbose_name='Video urlini kiriting')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavhani kiriting')),
                ('description', models.CharField(max_length=255, verbose_name='Qisqacha fikringizni kiriting')),
            ],
        ),
    ]
