# Generated by Django 4.2.9 on 2025-04-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_about_help_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
