# Generated by Django 5.2 on 2025-04-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_dailytransaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(verbose_name='Shu web-sayt haqingizda kiriting'),
        ),
    ]
